export const DESERT_CONFIG = {
  BLOCK: {
    MIN_LENGTH: 25,
    MAX_LENGTH: 150,
    MIN_HEIGHT: 15,
    MAX_HEIGHT: 20,
  },
  STAR: {
    MIN_HEIGHT: 50,
    MAX_HEIGHT: 150,
  },
  WATER_PROBABILITY: 0.35,
  FEATURE_PROBABILITY: 0.35,
} as const;
